name: .NET

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Pack
        run: dotnet pack --no-build -o .

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish NMediatController
        run: dotnet nuget push NMediatController.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.KEY }} --skip-duplicate

        
      - name: Publish NMediatController.ASPNET
        run: dotnet nuget push NMediatController.ASPNET.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.KEY }} --skip-duplicate