name: main

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Setup dotnet 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Format
        run: dotnet format --no-restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release

      - name: Pack
        run: dotnet pack --no-build -c Release -o .

      # - name: Publish MediatorBuddy
      #   run: dotnet nuget push MediatorBuddy.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.KEY }} --skip-duplicate

      # - name: Publish MediatorBuddy.AspNet
      #   run: dotnet nuget push MediatorBuddy.AspNet.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.KEY }} --skip-duplicate
